name: Build and Lint
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: yarn install
      - run: yarn run prepare

      - name: example router-redux-rematch
        working-directory: example/router-redux-rematch
        run: yarn run build

      - name: example simple
        working-directory: example/simple
        run: yarn run build

      - name: Look Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - run: npm install @jsdevtools/npm-publish -g
      - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/core/package.json

      - name: Is a tag created auto?
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./packages/core/package.json

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/react-dynamic-loadable@${{steps.create_tag.outputs.versionNumber}}/file/README.md) [![npm version](https://img.shields.io/npm/v/react-dynamic-loadable.svg)](https://www.npmjs.com/package/react-dynamic-loadable) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/react-dynamic-loadable)](https://bundlephobia.com/result?p=react-dynamic-loadable@${{steps.create_tag.outputs.versionNumber}})
            ```bash
            npm i react-dynamic-loadable@${{steps.create_tag.outputs.versionNumber}}
            ```

            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}
